name: cfBlazeProtect
main: ru.cronfire.cfBlazeProtect.cfBlazeProtect
version: 1.1
description: Plugin will protect your blaze spawners from griefing.
authors: [Zeluboba]
maintainer: Zeluboba
website: http://cronfire.ru/